import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("posts", "routes/posts.tsx"),
  route("posts/new", "routes/posts.new.tsx"),
  route("posts/:postId", "routes/posts.$postId.tsx"),
  route("posts/:postId/edit", "routes/posts.$postId.edit.tsx"),
  route("map", "routes/map.tsx"),
  route("map/report", "routes/map.report.tsx"),
  route("location/:id", "routes/location.$id.tsx"),
  route("me", "routes/me.tsx"),
  route("me/points", "routes/me.points.tsx"),
  route("me/bookmarks", "routes/me.bookmarks.tsx"),
  route("me/reports", "routes/me.reports.tsx"),
  route("ranking", "routes/ranking.tsx"),
  route("missions", "routes/missions.tsx"),
  route("notifications", "routes/notifications.tsx"),
  route("login", "routes/login.tsx"),
  route("register", "routes/register.tsx"),
  route("terms", "routes/terms.tsx"),
  route("faq", "routes/faq.tsx"),
  route("search", "routes/search.tsx"),
  route("admin", "routes/admin.tsx"),
  route("api/auth/login", "routes/api.auth.login.tsx"),
  route("api/auth/register", "routes/api.auth.register.tsx"),
  route("api/auth/logout", "routes/api.auth.logout.tsx"),
  route("api/auth/verify", "routes/api.auth.verify.tsx"),
  route("api/user/profile", "routes/api.user.profile.tsx"),
  route("api/user/points", "routes/api.user.points.tsx"),
  route("api/user/bookmarks", "routes/api.user.bookmarks.tsx"),
  route("api/user/reports", "routes/api.user.reports.tsx"),
  route("api/notifications", "routes/api.notifications.tsx"),
  route("api/posts", "routes/api.posts.tsx"),
  route("api/posts/list", "routes/api.posts.list.tsx"),
  route("api/posts/:postId", "routes/api.posts.$postId.tsx"),
  route("api/posts/:postId/comments", "routes/api.posts.$postId.comments.tsx"),
  route("api/posts/:postId/like", "routes/api.posts.$postId.like.tsx"),
  route("api/posts/:postId/bookmark", "routes/api.posts.$postId.bookmark.tsx"),
  route("api/ranking/:category", "routes/api.ranking.$category.tsx"),
  route("api/missions", "routes/api.missions.tsx"),
  route("api/map/rest-areas", "routes/api.map.rest-areas.tsx"),
  route("api/map/report", "routes/api.map.report.tsx"),
  route("api/search", "routes/api.search.tsx"),
  route("api/admin/users", "routes/api.admin.users.tsx"),
  route("*", "routes/not-found.tsx"),
] satisfies RouteConfig;
